version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./pgdata/:/var/lib/postgresql/data/
#    ports:
#      - "5432:5432"
    env_file:
      - ./.env
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  web:
#    image: mitroshinalex/yamdb_final_web:latest
    build: ../backend/foodgram/
    restart: always
    volumes:
      - static_value:/app/static_backend/
      - media_value:/app/media_backend/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static_value:/usr/share/nginx/html/static_backend/
      - media_value:/usr/share/nginx/html/media_backend/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - web
volumes:
  static_value:
  media_value:
